### ISSUE TITLE
Problem: this repo uses git submodules

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#178]
See https://github.com/artefactual/archivematica/issues/585.

**Comment by sevein** [comment]
This was fixed in qa/0.x (see #217).

**Comment by kellyannewithane** [comment]
@jrwdunham  Can you please test and comment if documentation changes are needed?

**Comment by sromkey** [comment]
@sevein does this need to be QA'd?

**Comment by jhsimpson** [comment]
I don't think this needs special qa attention.
