### ISSUE TITLE
Problem: DJANGO_STATIC_ROOT is unused

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#179]
There are two files that make use of `DJANGO_STATIC_ROOT`:

```
install/.storage-service
    export DJANGO_STATIC_ROOT=/var/archivematica/storage-service/assets

install/storage-service.gunicorn-config.py
    "DJANGO_STATIC_ROOT=/usr/lib/archivematica/storage-service/assets",
```

But it's not looked up from our settings, i.e. `storage_service/storage_service/settings/base.py` reads:

```python
STATIC_ROOT = normpath(join(SITE_ROOT, 'assets'))
```

I think we should update the files under `install/` to stop using it.

**Comment by jhsimpson** [comment]
PR #190 was merged, so this issue is resolved, closing.

**Comment by sromkey** [comment]
@sevein Does this need to be QA'd?

**Comment by sevein** [comment]
Nope.
