### ISSUE TITLE
Problem: CSS files reference to files which cannot be found

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#180]
For example:
- `css/jquery.dataTables.css` uses `images/back_enabled.png`
- `css/backbone-file-explorer.css` uses `img/folderopen.png`

There are more.

**Comment by sevein** [comment]
This is problematic when using WhiteNoise, i.e. makes `collecstatic` break.

**Comment by sevein** [comment]
Fixed in #217.

**Comment by sromkey** [comment]
@sevein does this need to be QA'd?

**Comment by sevein** [comment]
This has been already verified, thanks.
