### ISSUE TITLE
Problem: we're using synchronous workers

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#181]
This is a big issue when SS is doing I/O bound work because the workers block and wait instead of working on other requests.

I suggest to use `gevent` (add `gevent==1.2.1` in requirements) and run Gunicorn with `--worker-class  gevent`. It has to be tested.

**Comment by sevein** [comment]
If we move to `gevent` we'll also need a connection pool, more details here: https://goo.gl/fX7EUd.

**Comment by sevein** [comment]
Solved in #217.

**Comment by sallain** [comment]
@nickwilkinson please assign to a dev for testing

**Comment by nickwilkinson** [comment]
Hi @jraddaoui can you pleas test this?

**Comment by jraddaoui** [comment]
Hi @sevein, this looks amazing!

Some instructions on how to test it would be really helpful, as there are a lot of changes in that PR. I can see the following parts to test:

- Installation (Docker, Vagrant and packages)
- Environment changes (SS_DB_URL, ALLOWED_HOSTS , etc)
- Gunicorn and gevent configuration
- Log files
- Static files with Whitenoise
- Databases support

Do you think I should try the three install options and the three databases? And, after I get it installed and "working", what should I check?

- Verify that the SS interface is working well?
- Verify that a few transfers/ingests from the dashboard work as expected?

Thank you!

**Comment by kellyannewithane** [comment]
@jraddaoui  Yes, please work on the 3 install options and see how it goes?  Documentation will be needed, do you have suggestions as to where it should go?

**Comment by sevein** [comment]
Regarding to tests I think this is already been tested in many ways as it's part of the core of the application. I'll be looking at next steps for documentation.

**Comment by sevein** [comment]
See #294.
