### ISSUE TITLE
Problem: migrate should not create default user

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#182]
Instead, I think we can add a task that enables the operator to add a user as desired.

**Comment by ross-spencer** [comment]
Hi @sevein. Migration in this ticket, is it migration of packages, or the Django model?

**Comment by sevein** [comment]
I meant Django's `migrate`. Closing as it was superseded by https://github.com/artefactual/archivematica-storage-service/commit/2976d2526ddb3e680eeaca80b04c8dc5f80f8b0f fixed in v0.12.0.
