### ISSUE TITLE
Problem: SQLite is the only db backend supported (not distributed)

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#184]
In many situations it's desirable to use a distributed RDBMS like MySQL or PostgreSQL. There's probably not much stopping us from supporting them other than the limitations in our configuration system.

**Solution**

SQLite will stay as the default backend until a new major version of SS is released.

**Option 1:** add a new `SS_DB_ENGINE` environment variable. We would document which values are supported here, e.g. `django.db.backends.sqlite3` (default), `django.db.backends.mysql` and so on. 

```python
 DATABASES = {
      'default': {
          'ENGINE':  get_env_variable('SS_DB_ENGINE'),  # get_env_variable should take a default value
          # ...
      },
}
```

**Option 2:** look up new environment variable `SS_DB_URL` and parse it using [dj-database-url](https://github.com/kennethreitz/dj-database-url). When `SS_DB_URL` is used, the old environment strings (`SS_DB_NAME`, `SS_DB_USER`, `SS_DB_PASSWORD` and `SS_DB_HOST`) are ignored.

```python
DATABASES = {
    'default': dj_database_url.config(env='SS_DB_URL')
}
```

dj-database-url is very flexible. You can find many examples in [test_dj_database_url.py](https://github.com/kennethreitz/dj-database-url/blob/master/test_dj_database_url.py), e.g. `mysql://bea6eb025ca0d8:69772142@us-cdbr-east.cleardb.com/heroku_97681db3eff7580?reconnect=true`.

**Comment by sevein** [comment]
Fixed in #217.

**Comment by kellyannewithane** [comment]
@jhsimpson Document!

**Comment by sallain** [comment]
@jhsimpson bumping this - maybe there's a dev or sysadmin who could document the options that @sevein outlined above?

**Comment by sevein** [comment]
I'm doing this. Apparently https://github.com/artefactual/archivematica-storage-service/tree/stable/0.11.x/install doesn't list the SS_DB_* envs!
