### ISSUE TITLE
Problem: bag processes setting is not configurable

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#186]
See #177 for more details.

We should probably add a setting to django.settings that looks up the environment and it has a default, the one suggested in #177.

**Comment by sevein** [comment]
@jrwdunham fixed it here: #230.

**Comment by kellyannewithane** [comment]
documentation - installation - look at the code

**Comment by sallain** [comment]
@jrwdunham Does this need to go into the documentation somewhere?
