### ISSUE TITLE
Problem: packages tab rendering scalability

### ISSUE THREAD

**Issue by hakamine** [artefactual/archivematica-storage-service#205]
When displaying the packages/ location,  the Storage Service reads all the entries of the packages table to memory before rendering ( https://github.com/artefactual/archivematica-storage-service/blob/stable/0.10.x/storage_service/locations/views.py#L45-L47  ), even though the view shows only 10 packages at a time. On an instance with 40000+ packages it takes several minutes to display. Also fearing that eventually will get out of memory errors and become unable to display.

**Comment by ross-spencer** [comment]
Closing as this ticket was somewhat duplicated later on in https://github.com/archivematica/Issues/issues/676 and later resolved via https://github.com/artefactual/archivematica-storage-service/pull/470 so all should be good now! :tada: :tada: :tada:
