### ISSUE TITLE
Add create_user command (merge from Jisc fork)

### ISSUE THREAD

**Issue by helenst** [artefactual/archivematica-storage-service#209]
Merge work from https://github.com/JiscRDSS/archivematica-storage-service/pull/2

This adds a create_user management command to the storage service to help with automated deployment.

Related AM issue: https://github.com/artefactual/archivematica/issues/665

**Comment by lower29** [comment]
I have a dev branch based on `qa/0.x` ready to go for this. https://github.com/JiscRDSS/archivematica-storage-service/pull/2 is all new code and just a single commit so is straightforward to merge.

My only query is whether there is additional work required (e.g. to tests or ansible) that I'm not aware of.

**Comment by sevein** [comment]
Thank you guys!
