### ISSUE TITLE
Problem: menu bar does not highlight current page

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#219]
To recreate: Go to admin tab of SS and see that "Home" is highlighted.

**Comment by jrwdunham** [comment]
Should be fixed by https://github.com/artefactual/archivematica-storage-service/pull/273

**Comment by jrwdunham** [comment]
This is broken again as of Jan 26, 2018. I don't know why.

**Comment by sallain** [comment]
Looks good now.
