### ISSUE TITLE
Problem:  I can't run tests without installing database packages

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica-storage-service#222]
This recent commit https://github.com/artefactual/archivematica-storage-service/pull/217/commits/215cf1870cc4b4d3888a4d4f70092286c584b2f3

brought in support for mysql and postgresql as db backends, instead of just sqlite3.  

When running tests on this repo, sqlite3 is still used, and so it should not be necessary to install mysqlclient and other db related dependencies in the test environment.

This is important for running automated tests (travis) as well as for  testing locally (only source code checked out, not testing on a full deployed archivematica server).

**Comment by sevein** [comment]
Fixed in #223.
