### ISSUE TITLE
Problem: Arkivum version 4.2 requires md5 checksums

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica-storage-service#233]
#216 fixed an issue when storing AIP's in an Arkivum space.  However, that fix has introduced a new problem.  

When storing an AIP in Arkivum, the storage service first moves the AIP from it internal storage location to the Arkivum AIP Storage Location with operating system commands (rsync and a mv).  Afterwards, a checksum is POSTed to the Arkivum REST api, so that Arkivum can verify the contents were copied successfully before continuing with its processing.

After 216, the Arkivum model looks up the checksum for compresseed AIP's in the AIP's pointer file.  For uncompressed AIP's the bag manifest file is sent instead.  

Arkivum version 4.2 can process a range of checksum algorithms in bag manifest files, but for individual files (e.g., compressed AIPs) only md5 is supported.  

The Arkivum model needs to be updated to send only md5 for compressed AIPs.

**Comment by sevein** [comment]
@jhsimpson this is assigned to you. Are you planning to work on it?

**Comment by jhsimpson** [comment]
The newest version of Arkivum supports multiple checksum algorithms so this issue is no longer needed.
