### ISSUE TITLE
Problem: re-ingest error message is broken

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#237]
When you try to re-ingest a package that it has already been re-ingested the web interface reads the following message:

`Error re-ingesting package: This AIP is already being reingested on {pipeline}`

Instead of `{pipeline}` I would expect to see the name or the UUID of such pipeline.

**Comment by ross-spencer** [comment]
:tada: Adding `1.10` as this seems resolved by https://github.com/artefactual/archivematica-storage-service/commit/a8c7b7827d1e8082839ebba8b74f296cfc1e7fc0#diff-5f2ead45b8622f27e9b0bf6333334fff
