### ISSUE TITLE
Shibboleth user cannot login after the first logout

### ISSUE THREAD

**Issue by lwo** [artefactual/archivematica-storage-service#238]
In testing the archivematica/1.x and archivematica-storage-service/0.x branches we encounter the following issue when a user authenticates with the external identity provider method Shibboleth:

1. The user has never connected with the username
2. The user connects to the dashboard\storage service
3. The user is directed to the Shibboleth Identity Provider
4. The user authenticates
5. The user is directed to the dashboard\storage service
6. A local account is created for the user with the correct roles
7. The user operated the UI
8. The user does a logout
9. The Shibboleth service provider confirms the end of the session
10. The user closes the browser.
11 . The user opens the browser
12. The user repeats 2, 3, 4 and 5 but then the expected 7 does not occur.... in stead the user is presented with the native login screen of the dashboard\service provider and cannot proceed.

**Comment by sevein** [comment]
Thank you, @lwo. I've assigned this issue to @helenst as she is the most experienced person in the team in this area.

**Comment by helenst** [comment]
Looks like an issue with `django-shibboleth-user` - it sets a session key on logout to signal that re-login is not allowed in the same Django session (which can extend between browser sessions). (https://github.com/Brown-University-Library/django-shibboleth-remoteuser/blob/a336c2b715275b892bdc6234b043c7fd63dc97aa/shibboleth/views.py#L74) I think this is done to prevent a user being bounced straight back to a logged in state after logout on some setups, but not applicable here.

The fix should probably be to prevent that session key being set in the first place.
