### ISSUE TITLE
AIPs show in the storage service when not actually there

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica-storage-service#243]
Not able to download AIPs on Archival Storage tab because not stored where they should be on
http://am17x.qa.archivematica.org/

If logged into SS on am17x machine and go to the packages tab, shows that they're staged on the storage service and not uploaded.  They shouldn't be available on the archival storage tab.

**Comment by jrwdunham** [comment]
May be related to https://github.com/artefactual/archivematica/issues/815.

**Comment by jhsimpson** [comment]
This issues is fixed by https://github.com/artefactual/archivematica/issues/815
