### ISSUE TITLE
Problem: missing API endpoint to delete AIPs

### ISSUE THREAD

**Issue by hakamine** [artefactual/archivematica-storage-service#250]
Currently AIP deletions can only be done from the dashboard's Archival Storage tab. It is not possible to delete from the Storage Service directly (either via UI or API).

While in theory all AIPs are indexed and should appear in the Archival Storage, there are cases in which it would be useful to be able to delete an AIP not in Archival Storage.

A temporary workaround (to delete AIPs from the SS database not in the Archival Storage ) available  [here](https://github.com/artefactual-labs/ops-helpers/pull/6)

**Comment by ross-spencer** [comment]
Closing in favor of and updated https://github.com/archivematica/Issues/issues/1153 although if any component of this issue isn't described thoroughly enough, please do feel free to update the ticket details there.
