### ISSUE TITLE
Reingest broken: SS expects pointer file which isn't there

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#254]
Attempt a metadata-only re-ingest (or other type) on an AIP in Archivematica at qa/1.x. The storeAIP micro-service will issue a PUT request against the SS's Package resources, attempting to update the AIP, which ultimately calls `finish_reingest`. This breaks (returns a 500 response) because `finish_reingest` is expecting a pointer file from AM which is no longer present because recent changes to Archivematica have removed the pointer file creation micro-service and pointer file creation has been moved to the Storage Service.

See https://projects.artefactual.com/issues/11663

**Comment by jrwdunham** [comment]
We need to confirm that this is fixed by https://github.com/artefactual/archivematica-storage-service/pull/255.

**Comment by currmie** [comment]
Attempted metadata-only re-ingest and partial re-ingest on the following AIPs on am17x.qa:
Aip1 - 6214faf5-eab6-424c-b0f9-b1078e7c0828
Aip2 - 8ec6e3fd-586b-49c3-b31c-5038e6934677

Reingest of Aip1 fails at the Generate AIP METS microservice (runtime error: maximum recursion depth exceeded).
Reinsgest of Aip2 passes.

@jrwdunham, can you pls. advise?

**Comment by jrwdunham** [comment]
@currmie I've looked into your Aip1 failure and it seems to be due to another subtle bug in metsrw which I've documented as https://github.com/artefactual-labs/mets-reader-writer/issues/37. I will look into it more soon.
