### ISSUE TITLE
Enhancement: automatic check for django migrations

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica-storage-service#263]
Sometimes new Pull Reqests add code that requires a django migration to be run. It would be very helpful to add a travis check for this to all PR's.

This tool might do the job:
https://github.com/rev112/django-migration-checker

See: artefactual/archivematica#797 - same issue for Archivematica dashboard

**Comment by sevein** [comment]
I did something similar in fpr-admin, here: https://github.com/artefactual/archivematica-fpr-admin/blob/677607a38ed6d18bd8fa1601e1704a4096e30afe/.travis.yml#L7-L15.

**Comment by jrwdunham** [comment]
Fixed by https://github.com/artefactual/archivematica-storage-service/pull/277
