### ISSUE TITLE
Problem: pipeline self-registration mechanism is static

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#266]
When a new pipeline is registered, SS guesses the IP address by looking at the REMOTE_ADDR header of the HTTP request. This mechanism has worked fine for a long time because the pipeline was either running in the same host or in a separate host with a static IP address. In more dynamic environments IP addresses may change often and SS eventually becomes unable to reach the pipeline back, for example, for re-ingest.

In JiscRDSS [this issue was temporary solved](PIPELINE_REMOTE_NAME) by adding a new environment variable `PIPELINE_REMOTE_NAME` - this environment is defined in [rdss-archivematica](https://github.com/JiscRDSS/rdss-archivematica/pull/103). This enables us to use DNS names instead which works as long as the DNS server is up to date and the TCP port is always the same across al the replicas.

**Comment by sevein** [comment]
Temporary the SS admin can manually update the remote name in the admin tab using a DNS name, e.g. in our Compose environment the user can use the name `archivematica-dashboard`.

![image](https://user-images.githubusercontent.com/606459/32983679-5772147e-cc4d-11e7-917d-6c355a58ce5e.png)

**Comment by sevein** [comment]
Long-term solutions like the self registration pattern in service discovery should be considered. A simpler solution could be to allow the pipeline to define its own address. Instead of remote name we should we store the base URL, e.g. `https://archivematica-dashboard:8080`?

**Comment by sromkey** [comment]
@sevein does the referenced PR close this issue?

**Comment by sevein** [comment]
Yay.
