### ISSUE TITLE
Problem: extract_file endpont may fail to delete temporary folder

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#269]
The `/api/v1/file/<uuid>/extract_file/` endpoint uses the following code to extract a compressed package:

    (extracted_file_path, temp_dir) = package.extract_file(relative_path_to_file)

Then it runs the following to stream the contents of the file to the client:

```
response = http.FileResponse(open(filepath, 'rb'))
if temp_dir and os.path.exists(temp_dir):
    shutil.rmtree(temp_dir)
return response
```

I guess this approach works because the interpreter holds the file descriptor even when the files are deleted by `shutil.rmtree` meaning that the interpreter can still read the contents of the file. Eventually when the transfer completes Django would release the file descriptor for us and the operative system would be able to claim the space.

However it's been reported by a client a problem creating a new AIC and the logs showed the following:

```
Traceback (most recent call last):
  File "/usr/share/python/archivematica-storage-service/local/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 91, in wrapper
    result = func(resource, request, bundle, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 655, in extract_file_request
    response = utils.download_file_stream(extracted_file_path, temp_dir)
  File "/usr/lib/archivematica/storage-service/common/utils.py", line 124, in download_file_stream
    shutil.rmtree(temp_dir)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/var/archivematica/storage_service/tmpGJtGYm/AIC_test_004-a2b1890f-c089-4d37-b96e-
39486f604445/data'
```

In this case, `shutil.rmtree` failed to delete the `data` sub-directory but I don't exactly how that can happen because the code shouldn't try to do so until it's empty (see https://github.com/python/cpython/blob/2.7/Lib/shutil.py).

I haven't been able to reproduce. One workaround could be to pass `ignore_errors=True` to `shutil.rmtree` (best effort). Or maybe pass an `onerror` so at least we can log it.

**Comment by sevein** [comment]
A client has reported that when using NFS and because the file isn't closed then NFS creates a hidden file upon its deletion that prevents rmdir from removing its temp directory.

**Comment by sevein** [comment]
Related: https://serverfault.com/questions/201294/nfsxxxx-files-appearing-what-are-those.

**Comment by sevein** [comment]
I'm going to submit a pull request addressing the issue by passing `ignore_errors=True` to `shutil.rmtree`. It was suggested to address it in the following way:

```python
f = open(filepath, 'rb')
response = http.FileResponse(f.read())
f.close()
```

But I want to avoid that because I don't want to read the whole file in memory.

A long-term solution has been suggested in  https://github.com/artefactual-labs/am/issues/21 but it's not something we can achieve in the way SS works today.

**Comment by sromkey** [comment]
@sevein how can this be QA'd? Thanks.

**Comment by sevein** [comment]
This was reproducible only when the Archivematica Shared Directory was a NFS device.

I'm not sure if the QA environment is using NFS. If that was the case, we would need to send requests to the `/api/v1/file/<uuid>/extract_file/` endpoint (Storage Service) and verify that it does not throw an error. One of our clients was also able to reproduce this just by creating a new AIC in AM because that workflow was making use of the `/api/v1/file/<uuid>/extract_file/` endpoint.

This may require some coordination with @mamedin or @scollazo and tweaks in the QA environment, i.e. NFS drive instead of local filesystem.
