### ISSUE TITLE
Problem: double replications being created from the first replication, not the original

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica-storage-service#270]
To reproduce:
- create an AIP storage location which has 2 replicating locations
- Store an AIP in the location

Result:
The second replication will be created from the first replication, rather than from the original AIP. If you look at the pointer files for the original and replicated AIPs:
- original AIP has one replication event resulting in the first replication
- first replication also has a replication event resulting in the second replication

Instead, the original AIP pointer file should have two replication events and two corresponding validation events.

**Comment by joel-simpson** [comment]
@sromkey I tagged this with the triage-release-1.10 label because it was fixed for a client project (NHA) and PR has been completed, so better to have this merged sooner rather than later.

**Comment by cole** [comment]
> Instead, the original AIP pointer file should have two replication events and two corresponding validation events.

After discussion, this isn't quite true for validation events, as the validation events are in the pointer files for the replica AIPs. The behaviour we want (I think) is:
1. The original pointer file should contain one replication event per replica
2. Each replica should contain one validation event
3. Replica pointer files don't contain replication events, creation is used instead.

**Comment by joel-simpson** [comment]
The PR for this is merged so this looks like it can be moved over to 'review'... changing status now.

**Comment by sallain** [comment]
What a weird issue.

I think this is accurate now, though I just want to confirm the acceptance criteria, @sromkey.

My storage setup has a standard AIP storage location, plus two replicator locations which are both connected to the standard location

![Screenshot of Archivematica Storage Service.jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/93454c3c-1cd6-4f41-9b3d-0fa8d8897fe7/Screenshot+of+Archivematica+Storage+Service.jpg)

When I store an AIP in the standard location, two replications are created.

The pointer files contain the following info:

* The pointer file for the original has two replication PREMIS events (one for each replication)
* The pointer file for the original does not have any validation events
* The pointer files for the replications each have a validation event that says they have been validate against the original

That all seems correct to me, but just want a second set of eyes on it!
