### ISSUE TITLE
Problem: Archivematica cannot start transfers from encrypted transfer source locations

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica-storage-service#296]
If content is in an encrypted transfer source location, Archivematica cannot start transfers from it when arranged from backlog. This error appears in the dashboard logs when it is attempted:

`ERROR     2017-12-21 21:13:25  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /filesystem/copy_from_arrange/
Traceback (most recent call last):
 File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/share/archivematica/dashboard/components/filesystem_ajax/views.py", line 436, in copy_from_arrange_to_completed
   status_code, response = copy_from_arrange_to_completed_common(filepath, sip_uuid, sip_name)
 File "/usr/share/archivematica/dashboard/components/filesystem_ajax/views.py", line 505, in copy_from_arrange_to_completed_common
   (sip, error) = storage_service.get_files_from_backlog(files)
 File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 240, in get_files_from_backlog
   return copy_files(backlog, processing, files)
 File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 223, in copy_files
   LOGGER.warning("Unable to move files with %s because %s", move_files, e.content)
AttributeError: 'HTTPError' object has no attribute 'content'`

In the same way that the Storage Service will decrypt an AIP when it is requested by the dashboard, it needs to do the same for transfers.

Justin notes: "my guess is that the problem is here: https://wiki.archivematica.org/Storage_Service_API#Move_files_to_this_location the storage service api call being made when finalizing a sip is to this move_files endpoint
it is not a move_package call (we don't have that) so the move_files endpoint doesn't pay attention to the Space the files are in"

**Comment by sromkey** [comment]
@currmie We're going to be setting up a specific testing server to test encryption related issues.

**Comment by jrwdunham** [comment]
@sromkey I do not understand this issue. An encrypted space can only have locations with the following purposes:

- AIP Storage
- Transfer Backlog
- Replicator

Is this issue the same as https://github.com/artefactual/archivematica-storage-service/issues/301? If so, then this should be closed by the merging of https://github.com/artefactual/archivematica-storage-service/pull/302.

**Comment by sromkey** [comment]
@jrwdunham It's a duplicate of #301, I didn't realize that we both filed the same issue. I'll close now.

**Comment by currmie** [comment]
@sromkey - Has a testing server been set up to test encryption related issues?
