### ISSUE TITLE
Problem: gunicorn gevent worker class and sword API multiprocessing are incompatible

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#312]
Using gunicorn with worker class `'gevent'` is incompatible with usage of Python's multiprocessing package, which is used in the sword API logic at https://github.com/artefactual/archivematica-storage-service/blob/stable/0.11.x/storage_service/locations/api/sword/helpers.py#L148. For reference, see

- https://github.com/benoitc/gunicorn/issues/1367#issuecomment-268439104
- https://stackoverflow.com/questions/8678307/gevent-monkeypatching-breaking-multiprocessing

Related to https://github.com/artefactual/archivematica/issues/708.
Refs https://projects.artefactual.com/issues/11642.

The workaround is to set the gunicorn worker class to `'sync'` when SS's sword API is being used:

    $ export SS_GUNICORN_WORKER_CLASS=sync

However, a better fix is probably required here, i.e., some change to storage_service/locations/api/sword/helpers.py that can make concurrent HTTP requests without using `multiprocessing.Process`.

@sevein @jhsimpson any thoughts?

**Comment by sevein** [comment]
It could be implemented with threads too. Or we could wait until the work being done at https://github.com/hudmol/archivematica-storage-service/commit/async is completed.

**Comment by jrwdunham** [comment]
Note: for AM 1.7 we simply documented this issue and described a deployment workaround. See https://github.com/artefactual/archivematica-docs/pull/75.

**Comment by sevein** [comment]
Let's try to use the new `async` module.

**Comment by sevein** [comment]
> Note: for AM 1.7 we simply documented this issue and described a deployment workaround. See artefactual/archivematica-docs#75.

Question: if #383 is merged how do you think we should update the docs? Should we make a distinction between SS v0.11 and SS v0.12 or should we just update archivematica-docs's branch 1.8 and assume there that the user is using SS v0.12?

**Comment by sevein** [comment]
To test this we need to create a space of type "FEDORA via SWORD2". See https://wiki.archivematica.org/Storage_Service#FEDORA_Deposit for more details.

The deposits should work regardless the value used in the configuration attribute `SS_GUNICORN_WORKER_CLASS`. In fact this configuration attribute has been removed.

**Comment by currmie** [comment]
Hi  @sevein , has someone already created a space of type "FEDORA via SWORD2" that I could use for QA/testing?

**Comment by sevein** [comment]
@currmie this is a tough one because we don't have an environment for this. It's possible that the client has one. Perhaps @dcraze or @sromkey can help you.

**Comment by dcraze** [comment]
@currmie This is a COPPUL customer so they do not have a test environment.  @sevein @sromkey Not sure what it would take to create a test environment?

**Comment by sromkey** [comment]
We discussed this and we're not able to set up the correct test environment. We've moved it to verified but can re-open if anything comes up in other deployments.
