### ISSUE TITLE
Problem: there is no way to delete stored DIPs

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica-storage-service#319]
While you can request the deletion of an AIP from the dashboard and complete the deletion in the Storage Service, there is no such functionality for stored DIPs. I'm of the opinion that the two-step process for deleting AIPs (request in the dashboard, complete in the Storage Service) is not necessary for deletion of stored DIPs because if a DIP is accidentally deleted, it can always be regenerated by re-ingesting the AIP. We should add a delete option to the stored DIPs in the Packages tab.

**Comment by sevein** [comment]
We've agreed to implement it as follows:
> Delete button to be added to the SS so the deletion is initiated from there rather than through the API.

**Comment by sevein** [comment]
For QA, the delete dip button appears in the package list of the Storage Service. The workflow is a bit different from AIP deletion. In this case, a dialog appears requesting the user to confirm the removal of the package.
