### ISSUE TITLE
Problem: `pipeline.approve_transfer` called with wrong args

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#322]
On line 353 of api/sword/helpers.py the call `pipeline.approve_transfer(deposit.current_path, type='standard')` uses kwarg `type` when it should use `transfer_type`, cf. `pipeline.py::approve_transfer`. This breaks the Sword API.

**Comment by jrwdunham** [comment]
If this needs to be documented for the 1.7 release, it would be in the context of using the Sword API, especially as it relates to the Archidora (Arhivematica Islandora integration) project. Refs internal https://projects.artefactual.com/issues/11642.

**Comment by sromkey** [comment]
@jrwdunham is there any way to QA this without Archidora?

**Comment by jrwdunham** [comment]
@sromkey It looks like not. It looks like the following types of POST HTTP requests to various Sword endpoints will trigger the problematic code path that was fixed by PR 323.

1. Example POST finalization of deposit:

    $ curl -v -H "In-Progress: false" --request POST http://127.0.0.1:8000/api/v1/file/149cc29d-6472-4bcf-bee8-f8223bf60580/sword/

2. Example POST adding files to the deposit:

    $ curl -v -H "In-Progress: true" --data-binary @mets.xml --request POST http://127.0.0.1:8000/api/v1/file/149cc29d-6472-4bcf-bee8-f8223bf60580/sword/

3. Example POST of METS with file info:

    $ curl -v -H "Packaging: METS" -H "In-Progress: true" --data-binary @mets.xml --request POST http://127.0.0.1:8000/api/v1/file/9c8b4ac0-0407-4360-a10d-af6c62a48b69/sword/media/

4. Example POST creation of deposit, allowing asynchronous downloading of object content URLs:

     $ curl -v -H "In-Progress: true" --data-binary @mets.xml --request POST http://localhost:8000/api/v1/location/96606387-cc70-4b09-b422-a7220606488d/sword/collection/

The fix was just changing a typo in a method parameter name. This was introduced in Nov 2017 by a refactor PR; see https://github.com/artefactual/archivematica-storage-service/commit/e91aeb8aa06ca9775915e79ddda617bd0d160044#diff-493e5f2852dc4b55bc41ac4a243f8dc1R353.

I've grepped the code for any other cases where the problematic `Pipeline().approve_transfer` method is called and there are no more. Given the above and that it fixed a known issue for a client using Archidora, I'm quite confident that this can be moved to the Done column without needing further QA.
