### ISSUE TITLE
Problem: we are using `async` as a variable name when it is a reserved keyword in python >= 3.5

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#331]
See https://github.com/artefactual/archivematica-storage-service/blob/qa/0.x/storage_service/locations/api/resources.py#L441

**Comment by sevein** [comment]
CC @marktriggs

**Comment by marktriggs** [comment]
Drat!  Thanks.  Will send a PR for this.

**Comment by jrwdunham** [comment]
For QA nothing should be necessary here. Resolution of this issue simply involved changing some variable names. There should be no functional result noticeable to the user.

**Comment by nickwilkinson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jisc RDSS](https://trello.com/c/LGTIS5UR/9-jisc-rdss)
