### ISSUE TITLE
Problem: we are using old-style Python classes

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#332]
This should avoided in general. For the culprits, see:

storage_service/locations/models/async_manager.py
39:class RunningTask():
48:class AsyncManager():

storage_service/storage_service/urls.py
38:    class shibboleth_urls:

storage_service/common/middleware.py
17:class LoginRequiredMiddleware:

storage_service/locations/views.py
64:class PackageRequestHandlerConfig:

**Comment by ross-spencer** [comment]
@jrwdunham would this be the most appropriate doc about what this means? https://wiki.python.org/moin/NewClassVsClassicClass

**Comment by jrwdunham** [comment]
@ross-spencer that one looks good. I was hoping to find a clear-cut example of a code snippet showing how old-style classes can cause unexpected results. I found this: https://bugs.python.org/issue21785, but it seems pretty arcane. I think we should in general just have a policy that our classes are new-style across the board, even if it is motivated by an appeal to authority ultimately. Here's one potential gotcha taken from that ref above:

    >>> class A:
    ...      def __getitem__(self, index):
    ...          return True
    ... 
    >>> A()[-1]
    True
    >>> A()[-1:2]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: A instance has no attribute '__len__'
    >>> class B(object):
    ...      def __getitem__(self, index):
    ...          return True
    ... 
    >>> B()[-1]
    True
    >>> B()[-1:2]
    True

**Comment by jrwdunham** [comment]
Fixed by https://github.com/artefactual/archivematica-storage-service/pull/338
