### ISSUE TITLE
Problem: OSError is polluting the logs

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#336]
The SS very often tries to move files locally and falls back to rsync if an exception is raised. Since this is a common path, it seems odd to write the expected Python exception and traceback to the logs. I believe that this is an annoying red herring for people scanning the logs for errors when debugging. I suggest that we simply remove the two relevant `, exc_info=True` strings in space.py.

These are the kinds of log lines I don't think we should have:

    Traceback (most recent call last):
      File "/src/storage_service/locations/models/space.py", line 481, in move_rsync
        os.rename(source_norm, dest_norm)
    OSError: [Errno 18] Invalid cross-device link

This code was introduced in https://github.com/artefactual/archivematica-storage-service/pull/104

**Comment by jrwdunham** [comment]
Fixed by https://github.com/artefactual/archivematica-storage-service/pull/337

**Comment by jhsimpson** [comment]
This is already fixed in qa/0.x, but I am re-opening it now so that fix can be back-ported to stable/0.11.x and included in the 0.11.1 release.
