### ISSUE TITLE
Problem: rsync v. 3.1.0 may be leaving behind fixity-check-breaking temporary files

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#345]
A [known bug in rsync v. 3.1.0](https://unix.stackexchange.com/a/276710) can result in 0-byte files being left behind if the rsync process is interrupted. This will break fixity checking in uncompressed AIPs because BagIt validate will see these empty (`.`-prefixed) files and will determine the bag/AIP is invalid. This issue was recognized by a client (CCA, see internal Redmine 12145).

Right now, the idea that rsync 3.1.0 is responsible is just a hypothesis. The "store AIP" (rsync-using) process does not appear to have been interrupted on the machine where the bug was observed. However, the signature of the stray file—prefixation with `.`, suffixation with a six-digit base64 string like `.123EjZ`, having 0 bytes—seems to match the rsync bug description.

rsync 3.1.0 is the default in Ubuntu 14.04 and rsync 3.1.1 is the default in Ubuntu 16.04. We may have to create our own packages for rsync >3.1.0 for Ubuntu 14.04.

Assuming, rsync 3.1.0 is the culprit, resolving this issue would entail:

- modifying the [osdeps](https://github.com/artefactual/archivematica-storage-service/tree/stable/0.11.x/osdeps) files in SS to require rsync >3.1.0.
- modifying [am-packbuild](https://github.com/artefactual-labs/am-packbuild) to do the same.
- modifying [the SS Dockerfile](https://github.com/artefactual/archivematica-storage-service/blob/qa/0.x/Dockerfile) to do the same.

@sevein @scollazo @hakamine do you have any thoughts on this, either in terms of whether requiring rsync >3.1.0 would be difficult or in terms of whether this should be part of the 0.12.0 release?

**Comment by sevein** [comment]
@jrwdunham that's really good detective work! Moving to v3.1.1 or newer seems reasonable.

> Assuming, rsync 3.1.0 is the culprit, resolving this issue would entail:
> - modifying the osdeps files in SS to require rsync >3.1.0.
> - modifying am-packbuild to do the same.
> - modifying the SS Dockerfile to do the same.

I believe that as we're managing OS dependencies today we would be just adding the new version of the rsync package to AM v1.8's ubuntus-extra repo. IMO it's not ideal but I don't think that there is an alternative at the moment. This is something that we should probably discuss further.

**Comment by sevein** [comment]
We're going to add the version requirement in osdeps - the idea is to add a constraint with the minimum version selection, e.g. in this particular case, `version=3.1.1`.

**Comment by sromkey** [comment]
We need to make this package available in our repos so that it's included in Ubuntu and CentOS installations. I'm changing the assignee to @scollazo for now.

**Comment by jhsimpson** [comment]
I think this issue should not be in scope for the 1.7.2 or future releases.

Centos 7 provides rsync 3.1.2
https://centos.pkgs.org/7/centos-x86_64/rsync-3.1.2-4.el7.x86_64.rpm.html

Ubuntu 16.04 provided rsync 3.1.1 https://packages.ubuntu.com/xenial/rsync

Only Ubuntu 14.04 does not have a version of rsync above 3.10 available.

I don't think Archivematica 1.7.2 or higher should officially support
Ubuntu 14.04.

For Archivematica users still using Ubuntu 14.04 (regardless of the version
of Archivematica), there is a work around available (backport the 16.04
package to 14.04, or find a ppa that has the backport available).

Example:
https://opensourcehacker.com/2013/03/20/how-to-backport-packages-on-ubuntu-linux/
