### ISSUE TITLE
Problem: locations can't be created via the SS API

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#367]
This is something that we made possible in the JiscRDSS fork and we want to bring to vanilla:
https://github.com/JiscRDSS/archivematica-storage-service/pull/24. It enables deployments of Storage Service with customized storage configurations in an automated way.

This is an usage example available at JiscRDSS/rdss-archivematica: https://github.com/JiscRDSS/rdss-archivematica/blob/1f6cac40306e5ac56b24f3e39b794036fa0bac3f/compose/qa/etc/rdss-create-storage-locations.py.

---

E.g., given the following details:
- A pipeline `/api/v2/pipeline/90707555-244f-47af-8271-66496a6a965b/`
- A space: `/api/v2/space/141593ff-2a27-44a1-9de1-917573fa0f4a/`

We want to create a location as follows:

```shell
curl -s -d '{
    "pipeline": ["/api/v2/pipeline/90707555-244f-47af-8271-66496a6a965b/"],
    "purpose": "TS",
    "relative_path": "path/foo/bar",
    "description": "foobar",
    "space": "/api/v2/space/141593ff-2a27-44a1-9de1-917573fa0f4a/"
}' \
    -X POST \
    -H "Authorization: ApiKey test:test" \
    -H "Content-Type: application/json" \
        "http://127.0.0.1:62081/api/v2/location/" | \
            jq -r ".resource_uri"
```

The output of the previous command would be similar to the following:

    /api/v2/location/693f8fa4-744a-4c8f-9e1f-275d422e3bad/

**Comment by nickwilkinson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jisc RDSS](https://trello.com/c/LGTIS5UR/9-jisc-rdss)

**Comment by joel-simpson** [comment]
I tested creating locations of several types (backlog, transfer source, AIP Storage). I also created the actual directories and then using those locations (e.g. to start a transfer, and to store an AIP).
I tested setting locations with default = true and default = false.
All worked as expected.
