### ISSUE TITLE
Problem: waffle does not display closed issues more than a month old

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#373]
If we are trying to use Waffle to manage the 0.12.0 release, it is difficult to determine what is in scope for that release if closed issues that are more than one month old are not displayed. For example, https://github.com/artefactual/archivematica-storage-service/issues/332 is closed and is tagged with the 0.12.0 milestone but it will not be displayed in https://waffle.io/artefactual/archivematica?source=artefactual%2Farchivematica-storage-service&milestone=0.12.0

This may be solvable by adding a new column to hold these old closed issues. Or we may need to re-open such issues so that they are visible in Waffle.

**Comment by jrwdunham** [comment]
This waffle issue is relevant: https://github.com/waffleio/waffle.io/issues/314.

The suggestion at https://github.com/waffleio/waffle.io/issues/314#issuecomment-51905573 is relevant: basically "add another *Closed* column".

**Comment by jrwdunham** [comment]
The solution we seem to be settling on is to use the `Connected to #NNN` referencing from PRs to issues so that merging a PR does not close the #NNN issue. Once a PR is merged and it fixes an issue, that issue is put into the "Review" column of the Waffle board. Only after QA is complete do we close the issue and move the issue and PR(s) to the "Done" column

**Comment by sallain** [comment]
@jrwdunham We've implemented the above - there's now a "Verified" column where merged and QA'd issues can sit until they've been released. Once an issue is in a release, it can be moved to the Done column, where it will disappear in 30 days. This should resolve the issue!
