### ISSUE TITLE
Problem: long-running API calls are synchronous (need async)

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#374]
API calls to the Storage Service which request the creation of packages or the moving of packages are synchronous. This means the caller must wait on an open HTTP connection while the long-running operation executes. This is problematic because it will inevitably cause timeouts and because the client is blocked from performing other actions.

Parent of #358
Parent of #331

**Comment by nickwilkinson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jisc RDSS](https://trello.com/c/LGTIS5UR/9-jisc-rdss)
