### ISSUE TITLE
Problem: this project can't replace RDSS's fork yet

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#375]
RDSS wants to switch to vanilla SS but it can't because the three issues listed below haven't been addressed yet.

Similar issue in AM: https://github.com/artefactual/archivematica/issues/1127.

Dependencies:
- [x] Parent to #367 (PR #368).
- [x] Parent to #286 (PR #364).

Related: https://jiscdev.atlassian.net/browse/RDSSARK-521.
Fork's address: https://github.com/JiscRDSS/archivematica-storage-service.

**Comment by nickwilkinson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jisc RDSS](https://trello.com/c/LGTIS5UR/9-jisc-rdss)
