### ISSUE TITLE
Problem: unable to request deletion for uncompressed AIPs

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica-storage-service#376]
When a request for deletion of an uncompressed AIP (no pointer file) is launched, nothing happens.

The deletion request works when triggered from the dashboard.

**Comment by ross-spencer** [comment]
@scollazo I was just taking a brief look at this today out of curiosity. I wonder if it was related to, or at least resolved by https://github.com/artefactual/archivematica-storage-service/pull/460 as it seems to have been resolved in the latest storage service commits from a brief test. What do you reckon?

**Comment by ross-spencer** [comment]
Closing as this looks resolved. 

1. Selected the option to create an uncompressed AIP in the dashboard.
2. Created an uncompressed AIP.
3. Verified it had no pointer file.
4. Requested deletion in the storage service (the JS message popped up).
5. Followed-through to complete the deletion procedure. 

Package was recorded as deleted in the storage service as expected. 

Closing, but if it is discovered this is closed in error we can reopen or revisit in the https://github.com/archivematica/issues repo.
