### ISSUE TITLE
Problem: referential integrity in db may be breakable with SQLite

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#387]
On a certain client's SS deploy which uses SQLite, a Pipeline row was somehow deleted even though a Package row was still referencing it as its origin pipeline. This should not be possible via Django/GUI, although the SQLite CLI will not prevent it. Tests should be performed to determine whether API calls or GUI actions can break referential integrity.

This post may be relevant: https://stackoverflow.com/questions/6745763/enable-integrity-checking-with-sqlite-in-django

**Comment by jrwdunham** [comment]
## Experimental results: Referential Integrity

- The SS GUI will prevent a user from deleting a pipeline that is the origin of one or more packages; see storage_service/locations/views.py.
- The Django shell will allow such a deletion and all related packages (and locations) will be deleted as well (cascade).
- The MySQL CLI will prevent the deletion, a foreign key constraint will fail.
- The SQLite CLI will allow such a deletion, unless you call `PRAGMA foreign_keys = ON;`:

          sqlite> PRAGMA foreign_keys = ON;
          sqlite> delete from locations_pipeline;
          Error: FOREIGN KEY constraint failed

  This can be configured via the SQLite config file::

          echo "PRAGMA foreign_keys = ON;" > ~/.sqliterc

**Comment by jrwdunham** [comment]
@jhsimpson @sevein @scollazo hoping one of you might have time to read the above and give input on what, if anything, you think can/should be done. @scollazo this is related to internal RM 12176.

The solution may just be to use MySQL for the SS db in future deploys.

My concern is that somehow a client got their SS db into a broken state, and that the SQLite CLI was the tool used. Maybe enabling `foreign_keys` in our Ansible and package deploy logic is warranted here. Thoughts?

**Comment by sevein** [comment]
FWIW, Django didn't start using SQLite foreign key constraints until Django v2.0.
See https://github.com/django/django/commit/169c3b3e07829d9ffa409b6eb5c1094d8ef918a8.

I would just advise users not to use the CLI unless they know what they're doing. A better solution IMO is to use the shell at all times which also ensures other guarantees like signal callbacks are being processed, etc.

**Comment by sevein** [comment]
@jrwdunham ok I didn't read carefully.
Should we add the pragma manually when we establish the connection?
I've found this example that uses signals: https://stackoverflow.com/a/6843199.

**Comment by jrwdunham** [comment]
I am closing this issue. Developers and sysadmins should not use the SQLite CLI to modify the database unless they are very careful. It is too easy to break referential integrity with SQLite but putting safeguards in place to make the SQLite CLI more safe is not worth the effort.
