### ISSUE TITLE
Problem: packages cannot be stored in DSpace via its REST API

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#391]
The [current DSpace space](https://github.com/artefactual/archivematica-storage-service/blob/stable/0.11.x/storage_service/locations/models/dspace.py) makes requests to DSpace using the SWORD2 protocol. Some users of Archivematica (the Storage Service) need to make use of the DSpace REST API.

**Comment by currmie** [comment]
Verified. Also, see https://github.com/artefactual/archivematica-storage-service-docs/pull/12 for corresponding SS documentation updates.
