### ISSUE TITLE
Files array in /api/v2/file/<UUID>/contents/ empty

### ISSUE THREAD

**Issue by federicolucca** [artefactual/archivematica-storage-service#427]
Goodmorning 
I'm trying to get the list of the files in a package AIP/DIP throw this API  /api/v2/file/<UUID>/contents/ .
All the times return empty the array of files. Why? i created package with many files,i sure about that

Federico

**Comment by ross-spencer** [comment]
Hi there Federico, 

This is a great question. I actually just researched it recently, and had to log an issue as it doesn't seem to function as expected for all Storage Service locations: https://github.com/archivematica/Issues/issues/342

More information here: https://groups.google.com/d/msg/archivematica/SZyinU3Kq9U/Xkv7ZbxDAQAJ

I'll close this issue now in favor of the one on our [issues](https://github.com/archivematica/Issues/issues/) repository which is where we're currently migrating all GitHub issues relating to the Archivematica code-base. Feel free to continue the discussion there. 

Many thanks! 
Ross
